/*
1. Create tables and inserts for demo purposes: 20 - 255
2. Create SQL Login: 259
3. Tools: 278
4. Create database user: 325
5. Grants: 336
6. Other permissions/Revoke: 360
7. List Logins: 381
8. Recreate Logins: 402
9. Drop user / login: 433
*/


/*
Data generated by: https://www.mockaroo.com/
*** All the info from the people shown here is fake ***
*/
-- 1. Create tables
-- a. Drop table (if exists)
DROP TABLE IF EXISTS [CorporateData_Mountain1].[dbo].[SamplePeople]

-- b. Create table
CREATE TABLE [CorporateData_Mountain1].[dbo].[SamplePeople] (
	Id INT IDENTITY (1,1) PRIMARY KEY,
	First_Name VARCHAR(50),
	Last_Name VARCHAR(50),
	email VARCHAR(50),
	[Address] VARCHAR(80),
	Job_Title VARCHAR(50),
	Date_Hired DATE,
	[Remote] bit
);

-- c. Enable identity insert
SET IDENTITY_INSERT [CorporateData_Mountain1].[dbo].[SamplePeople] ON;

-- d. Insert 1,000 rows
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (1, 'Bell', 'Preble', 'bpreble0@globo.com', '16 BOULEVARD DES ITALIENS', 'Sales Associate', '11/23/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (2, 'Abagail', 'McCambridge', 'amccambridge1@sfgate.com', '400 HWY 52 BY-PASS WEST', 'Software Consultant', '2/29/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (3, 'Shelli', 'Tapton', 'stapton2@jiathis.com', '"LES NÉGADIS" AVENUE PAUL ARÈNE', 'Software Consultant', '10/9/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (4, 'Hartley', 'Bisgrove', 'hbisgrove3@ow.ly', '18 QUAI DE LA RAPEE', 'Sales Representative', '6/21/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (5, 'Jessamine', 'Carcas', 'jcarcas4@redcross.org', 'VIA EMILIA A SAN PIETRO, 4', 'Legal Assistant', '3/18/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (6, 'Yoshiko', 'Zoane', 'yzoane5@multiply.com', 'PO BOX 1037', 'Project Manager', '6/5/2023', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (7, 'Sully', 'Dressel', 'sdressel6@dailymotion.com', '1721 11TH AVE', 'Human Resources Assistant II', '10/17/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (8, 'Gui', 'Knipe', 'gknipe7@vk.com', '18 RUE SALVADOR ALLENDE CS 50307', 'Editor', '8/8/2023', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (9, 'Zollie', 'Bradnam', 'zbradnam8@mapquest.com', 'P O BOX 909', 'Staff Accountant II', '4/4/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (10, 'Rowan', 'Chicotti', 'rchicotti9@phpbb.com', '806 W. 5TH ST.', 'Internal Auditor', '9/16/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (11, 'Breanne', 'Skippings', 'bskippingsa@usnews.com', '80 SUGAR CREEK CENTER BLVD', 'Chemical Engineer', '7/19/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (12, 'Alaine', 'Chantler', 'achantlerb@quantcast.com', 'Im Heiligengarten 3', 'Biostatistician I', '11/11/2019', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (13, 'Willem', 'Iacovelli', 'wiacovellic@accuweather.com', 'P.O. BOX 85139', 'Quality Engineer', '1/12/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (14, 'Matelda', 'Tardiff', 'mtardiffd@pinterest.com', '28, Boulevard de Kockelscheuer', 'Help Desk Operator', '2/25/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (15, 'Gae', 'Pakes', 'gpakese@mozilla.org', 'AVENUE DE MONPELLIÉRET - MAURIN', 'Associate Professor', '12/5/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (16, 'Jamey', 'Geekie', 'jgeekief@ustream.tv', 'NY-31-17-0119', 'Structural Engineer', '11/26/2019', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (17, 'Tammy', 'Brookwell', 'tbrookwellg@nba.com', '1460 VALLEY ROAD', 'Financial Advisor', '7/20/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (18, 'Blinni', 'Curee', 'bcureeh@ehow.com', '12345 W COLFAX AVE', 'Operator', '6/23/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (19, 'Lin', 'Castanone', 'lcastanonei@spotify.com', 'PO BOX 32282', 'Geological Engineer', '11/1/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (20, 'Shelagh', 'Vickress', 'svickressj@netscape.com', 'Curraheen Road', 'VP Quality Control', '3/3/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (21, 'Lilyan', 'Ewestace', 'lewestacek@tripod.com', '18 Drumcondra Road Upper, Drumcondra', 'Assistant Professor', '3/22/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (22, 'Onfre', 'Blofeld', 'oblofeldl@netvibes.com', 'CL TUTOR, 16', 'Design Engineer', '9/29/2019', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (23, 'Nye', 'Francecione', 'nfrancecionem@acquirethisname.com', 'CORSO SICCARDI, 13', 'Office Assistant III', '9/9/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (24, 'Edith', 'Harcus', 'eharcusn@mail.ru', 'Coolsingel 139', 'Human Resources Manager', '9/18/2019', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (25, 'Bella', 'Jonin', 'bjonino@japanpost.jp', 'Untermarkt, 3', 'VP Accounting', '2/16/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (26, 'Gwendolen', 'Ledur', 'gledurp@nymag.com', '6TH FLOOR', 'Speech Pathologist', '3/29/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (27, 'Caz', 'McCall', 'cmccallq@cbc.ca', 'Grünrockstraße 5', 'Geological Engineer', '11/14/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (28, 'Scot', 'Hundey', 'shundeyr@miitbeian.gov.cn', 'ul. Wołoska 24', 'Sales Associate', '9/19/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (29, 'Justinian', 'Charville', 'jcharvilles@cornell.edu', 'VIA ANDREA DORIA, 17', 'Staff Accountant II', '7/17/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (30, 'Charlie', 'Fellman', 'cfellmant@theatlantic.com', '63 RUE DE LA VICTOIRE', 'Payment Adjustment Coordinator', '4/4/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (31, 'Dagmar', 'Lessmare', 'dlessmareu@deliciousdays.com', '102 DUFFY AVENUE', 'Graphic Designer', '4/23/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (32, 'Luelle', 'Willcocks', 'lwillcocksv@issuu.com', 'PIAZZA FILIPPO MEDA 4', 'Senior Cost Accountant', '4/1/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (33, 'Trina', 'Parrot', 'tparrotw@flavors.me', 'PO BOX 709', 'Cost Accountant', '2/22/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (34, 'Boothe', 'Phythien', 'bphythienx@cdbaby.com', 'EP-MN-WN1A', 'VP Quality Control', '7/11/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (35, 'Nikola', 'Huggill', 'nhuggilly@dell.com', '12 PLACE DES ETATS UNIS', 'Budget/Accounting Analyst I', '12/11/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (36, 'Charmane', 'Boncoeur', 'cboncoeurz@gnu.org', 'TOUR EUROPLAZA 20 AV ANDRÉ PROTHIN', 'Electrical Engineer', '5/20/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (37, 'Erwin', 'Carman', 'ecarman10@hc360.com', 'Mecklenburger Straße 9', 'VP Product Management', '8/1/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (38, 'Christin', 'Chrystie', 'cchrystie11@mac.com', '45-47 Ashe Street, Tralee,', 'Biostatistician III', '10/29/2023', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (39, 'Darcee', 'Temby', 'dtemby12@istockphoto.com', '1912 CHEROKEE AVENUE SOUTH WEST', 'Senior Quality Engineer', '12/23/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (40, 'Merridie', 'Dockwra', 'mdockwra13@unblog.fr', '411 THEODORE FREMD AVE SUITE 350', 'Geological Engineer', '1/31/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (41, 'Barde', 'Embling', 'bembling14@google.es', '900 HWY 62 NW', 'Geological Engineer', '5/1/2023', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (42, 'Magdalene', 'Creegan', 'mcreegan15@twitter.com', 'North Mall, Westport', 'Nuclear Power Engineer', '11/4/2019', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (43, 'Maura', 'Tapson', 'mtapson16@narod.ru', 'Raiffeisenplatz, 1', 'Analog Circuit Design manager', '7/30/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (44, 'Brenn', 'Riatt', 'briatt17@phoca.cz', 'Rynek Kleparski 8', 'Analog Circuit Design manager', '8/7/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (45, 'Adolphus', 'Vanderplas', 'avanderplas18@redcross.org', 'ENTREE 2 2 BOULEVARD DE L EUROPE', 'Business Systems Development Analyst', '10/28/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (46, 'Arabella', 'Naper', 'anaper19@vistaprint.com', '40, Avenue J.F. Kennedy', 'Staff Accountant I', '7/24/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (47, 'Camel', 'Farrey', 'cfarrey1a@a8.net', '7TH FLOOR - ACH', 'Software Test Engineer III', '6/15/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (48, 'Rivkah', 'McFarlan', 'rmcfarlan1b@miibeian.gov.cn', 'Hauptstr., 82', 'Geologist I', '5/19/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (49, 'Perl', 'Ovens', 'povens1c@cornell.edu', 'Main street, Blackrock, Dundalk', 'Senior Sales Associate', '11/23/2023', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (50, 'Umeko', 'Seamans', 'useamans1d@vimeo.com', 'CORSO ORBASSANO, 367', 'Office Assistant I', '3/24/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (51, 'Barbabas', 'Kliemann', 'bkliemann1e@unicef.org', 'Ing. Ludwig Pech-Straße, 1', 'Assistant Professor', '3/18/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (52, 'Gayler', 'Bickerton', 'gbickerton1f@dell.com', 'ul. Jagiellońska 17', 'Research Associate', '7/25/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (53, 'Margarette', 'Marney', 'mmarney1g@bluehost.com', 'PIAZZA FILIPPO MEDA 4', 'Staff Scientist', '11/29/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (54, 'Nickie', 'Liversedge', 'nliversedge1h@spotify.com', '386 MAIN ST', 'Assistant Manager', '12/31/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (55, 'Brittany', 'Kemer', 'bkemer1i@studiopress.com', 'PO BOX 85929', 'Accountant II', '12/13/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (56, 'Davin', 'Delepine', 'ddelepine1j@state.gov', '4400 LEWIS STREET', 'Computer Systems Analyst II', '4/3/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (57, 'Park', 'Jermy', 'pjermy1k@dion.ne.jp', '111 SYLVAN AVENUE', 'Developer II', '5/18/2023', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (58, 'Daphna', 'Djurdjevic', 'ddjurdjevic1l@sbwire.com', 'P O BOX 808', 'VP Accounting', '4/5/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (59, 'Clarence', 'Weddeburn', 'cweddeburn1m@drupal.org', '301 W. BROADWAY', 'Payment Adjustment Coordinator', '6/5/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (60, 'Zsazsa', 'Portigall', 'zportigall1n@usda.gov', '3200 WILSHIRE BLVD', 'Design Engineer', '7/27/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (61, 'Mar', 'Threadgill', 'mthreadgill1o@washington.edu', 'Luitpoldstraße 14', 'Programmer Analyst I', '9/2/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (62, 'Lanae', 'Yurocjhin', 'lyurocjhin1p@etsy.com', '500 ROSS ST.', 'Help Desk Technician', '7/22/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (63, 'Gran', 'Pick', 'gpick1q@goo.ne.jp', 'Credit Union House, Askea,', 'Accounting Assistant II', '9/21/2019', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (64, 'Fabe', 'Collier', 'fcollier1r@quantcast.com', '12 PLACE DES ETATS UNIS', 'Help Desk Operator', '4/15/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (65, 'Letti', 'Connick', 'lconnick1s@ocn.ne.jp', '15-17 O''Neill Street, Carrickmacross,', 'Director of Sales', '5/19/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (66, 'Kirk', 'MacMorland', 'kmacmorland1t@tmall.com', '101 S. 3RD AVE', 'Information Systems Manager', '10/13/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (67, 'Julina', 'Rummins', 'jrummins1u@comcast.net', 'P.O. BOX 70', 'Administrative Assistant I', '8/7/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (68, 'Emanuel', 'Cassells', 'ecassells1v@surveymonkey.com', '110 S FERRALL STREET', 'Food Chemist', '3/27/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (69, 'Fairleigh', 'Ricco', 'fricco1w@census.gov', 'Dorfstraße, 92', 'Analyst Programmer', '8/6/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (70, 'Gussy', 'Abeau', 'gabeau1x@xinhuanet.com', '100 N PHILLIPS AVE', 'Assistant Media Planner', '6/18/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (71, 'Robb', 'Dumphreys', 'rdumphreys1y@blogtalkradio.com', 'ATTN: PAMELA HOFFERT', 'Senior Cost Accountant', '10/30/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (72, 'Stavro', 'Abrahim', 'sabrahim1z@techcrunch.com', 'PO BOX 1578', 'Research Nurse', '10/8/2019', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (73, 'Sam', 'Lithgow', 'slithgow20@storify.com', 'Alte-Leipziger-Platz 1', 'Web Developer I', '7/2/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (74, 'Marya', 'Fransson', 'mfransson21@umich.edu', 'PO BOX 1377', 'Senior Financial Analyst', '5/31/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (75, 'Eward', 'Mahomet', 'emahomet22@4shared.com', '86, Aiolou Str.', 'Information Systems Manager', '4/23/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (76, 'Ward', 'Willis', 'wwillis23@webeden.co.uk', 'PZ DE SAN ANTONIO, SN', 'Nurse Practicioner', '2/25/2024', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (77, 'Berenice', 'Ipsly', 'bipsly24@dailymotion.com', '6, Patriarchou Ioakim and Karapanou Str.', 'Health Coach IV', '5/23/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (78, 'Curtice', 'Danielsohn', 'cdanielsohn25@slashdot.org', 'VIA G. MAZZINI, 152', 'VP Quality Control', '3/28/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (79, 'Natty', 'Balk', 'nbalk26@weibo.com', '102 BYPASS PLAZA', 'Analog Circuit Design manager', '4/11/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (80, 'Ronna', 'Wilmut', 'rwilmut27@usda.gov', '100 EAST BURLINGTON', 'Business Systems Development Analyst', '12/13/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (81, 'Janice', 'Strahan', 'jstrahan28@rambler.ru', 'EP-MN-WN1A', 'Structural Engineer', '7/30/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (82, 'Teresina', 'Sylvester', 'tsylvester29@example.com', 'P O BOX 709', 'Administrative Assistant I', '5/17/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (83, 'Lyn', 'Bridgett', 'lbridgett2a@ehow.com', '600 HWY 71 SOUTH', 'Account Executive', '12/20/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (84, 'Brett', 'Brevitt', 'bbrevitt2b@yandex.ru', 'Alte Landstraße 21a', 'Clinical Specialist', '8/15/2020', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (85, 'Cissy', 'Baudy', 'cbaudy2c@wix.com', '2020 ROSINA ST', 'Marketing Assistant', '12/14/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (86, 'Celestyn', 'Picard', 'cpicard2d@hubpages.com', 'Donauwörther Straße 9-13', 'Research Assistant IV', '6/9/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (87, 'Bennie', 'Hannond', 'bhannond2e@nature.com', '1000 W. DICKINSON', 'Research Nurse', '11/16/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (88, 'Seumas', 'Brokenshaw', 'sbrokenshaw2f@vistaprint.com', 'ul. Puławska 15', 'Engineer IV', '3/18/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (89, 'Sally', 'Strainge', 'sstrainge2g@printfriendly.com', '12 PLACE DES ETATS UNIS', 'Nurse Practicioner', '12/11/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (90, 'Flss', 'Rafe', 'frafe2h@cnbc.com', 'Pfauengasse 1', 'Recruiter', '2/25/2021', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (91, 'Hurley', 'Bradden', 'hbradden2i@marketwatch.com', 'Neusser Straße 5', 'Cost Accountant', '6/5/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (92, 'Giustina', 'Nellen', 'gnellen2j@geocities.jp', 'VIA LUCREZIA ROMANA, 41/47', 'Librarian', '7/24/2022', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (93, 'Donnamarie', 'Olpin', 'dolpin2k@hatena.ne.jp', '2 AVENUE GAMBETTA CS 60055 COURBEVOIE', 'Dental Hygienist', '11/3/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (94, 'Codee', 'Falconar', 'cfalconar2l@cocolog-nifty.com', 'Karspeldreef 6 A', 'Legal Assistant', '11/7/2020', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (95, 'Olivie', 'Viegas', 'oviegas2m@t-online.de', '101 N STATE ST', 'Cost Accountant', '6/11/2022', 0);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (96, 'Shirlene', 'Rembrandt', 'srembrandt2n@techcrunch.com', 'PO BOX 27025', 'Senior Sales Associate', '4/29/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (97, 'Debra', 'Druce', 'ddruce2o@kickstarter.com', 'P.O. BOX 1037', 'Teacher', '4/30/2024', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (98, 'Nathan', 'Freed', 'nfreed2p@patch.com', 'An der Sparkasse 1', 'Senior Sales Associate', '5/14/2021', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (99, 'Glyn', 'Sissons', 'gsissons2q@eventbrite.com', 'PIAZZA FILIPPO MEDA 4', 'VP Quality Control', '4/3/2023', 1);
INSERT INTO [CorporateData_Mountain1].[dbo].[SamplePeople] (id, First_Name, Last_Name, email, [Address], Job_Title, Date_Hired, [Remote]) VALUES (100, 'Florentia', 'Edbrooke', 'fedbrooke2r@sourceforge.net', 'Hauptplatz, 47', 'Graphic Designer', '6/21/2022', 0);
-- Disable identity insert
SET IDENTITY_INSERT [CorporateData_Mountain1].[dbo].[SamplePeople] OFF;

-- Select random data
Select Top 10 * From [CorporateData_Mountain1].[dbo].[SamplePeople] Order by NEWID() DESC;

-- Select count all
Select COUNT(*) [Total] From [CorporateData_Mountain1].[dbo].[SamplePeople];

create table [CorporateData_Mountain1].[dbo].[SampleProducts] (
	Prod_id INT,
	Prod_Desc VARCHAR(128),
	Prod_Dept VARCHAR(50),
	Prod_Color VARCHAR(50),
	Prod_Price VARCHAR(50),
	Prod_Expires DATE,
	Prod_Comments VARCHAR(128)
);
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (1, 'Leak-proof bottles for travel-sized toiletries.', 'Games', 'Red', 9.99, '10/7/2026', 'Higuillo De Limon');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (2, 'Crunchy granola clusters mixed with nuts and honey.', 'Industrial', 'Orange', 2.49, '12/1/2026', 'Silky Prairie Clover');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (3, 'Creamy ice cream with a warm cinnamon flavor, perfect for dessert.', 'Baby', 'Yellow', 4.99, '11/25/2026', 'Rock Onion');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (4, 'Stainless steel travel mug that keeps drinks hot or cold.', 'Movies', 'Violet', 24.99, '12/14/2026', 'Spike Quillwort');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (5, 'A fresh, flavorful basil pesto for pasta and more', 'Garden', 'Blue', 4.79, '9/23/2026', 'Forbes'' Pipturus');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (6, 'Small fridge designed to keep skincare products cool and fresh.', 'Kids', 'Yellow', 39.99, '10/1/2026', 'Firetree');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (7, 'Passive noise reduction headphones for focus.', 'Jewelry', 'Pink', 39.99, '12/7/2026', 'Rainier Violet');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (8, 'A stylish midi dress with stylish pleats, suitable for any occasion.', 'Computers', 'Turquoise', 79.99, '10/26/2026', 'Florida Slash Pine');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (9, 'Unsweetened frozen acai purée for smoothies and bowls.', 'Home', 'Fuscia', 6.99, '12/8/2026', 'Flower''s Orthotrichum Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (10, 'A flavorful lentil curry cooked with vegetables and spices.', 'Health', 'Blue', 4.49, '10/20/2026', 'Centipeda');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (11, 'Safe and easy-to-use nail clippers for pets.', 'Tools', 'Maroon', 12.99, '10/25/2026', 'Inflatedscale Flatsedge');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (12, 'Quick boiling kettle for small kitchens and dorms.', 'Clothing', 'Maroon', 29.99, '10/29/2026', 'Yellow Mombin');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (13, 'Soft and strong toilet paper for everyday use.', 'Computers', 'Mauv', 8.99, '10/25/2026', 'Wright''s Fabronia Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (14, 'Water-resistant Bluetooth speaker for showers.', 'Industrial', 'Maroon', 24.99, '11/4/2026', 'Summer Pheasant''s Eye');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (15, 'Canned pumpkin puree, perfect for pies and soups.', 'Home', 'Aquamarine', 2.99, '12/3/2026', 'Cactus Apple');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (16, 'A ready-to-eat soup with coconut milk, spices, and vegetables.', 'Health', 'Purple', 3.99, '10/10/2026', 'Schistidium Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (17, 'Marinated beef strips in teriyaki sauce for easy grilling.', 'Home', 'Khaki', 7.49, '12/13/2026', 'Bingen Lupine');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (18, 'Compact projector for movies and presentations on the go.', 'Health', 'Puce', 199.99, '10/7/2026', 'Dimerella Lichen');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (19, 'Eco-friendly cutting board that is safe for dishwashers.', 'Outdoors', 'Blue', 22.99, '11/15/2026', 'Petunia');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (20, 'Chic wrap jumpsuit that flatters the body and is perfect for any occasion.', 'Automotive', 'Turquoise', 54.99, '11/24/2026', 'Caper');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (21, 'Tangy goat cheese infused with herbs, perfect for snacking.', 'Games', 'Mauv', 5.49, '11/23/2026', 'Drummond''s Clematis');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (22, 'A refreshing blend of peaches and mangoes for a delicious smoothie.', 'Music', 'Green', 3.49, '11/10/2026', 'Rainbow Iris');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (23, 'UV light sanitizer for phones and small items.', 'Jewelry', 'Khaki', 39.99, '12/6/2026', 'Schaereria Lichen');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (24, 'Sanitary holder that ensures your toothbrush stays clean.', 'Computers', 'Goldenrod', 14.99, '10/1/2026', 'Rough Pipewort');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (25, 'Delicious soft cookies, dairy-free and egg-free, perfect for treats.', 'Toys', 'Mauv', 4.79, '11/6/2026', 'Larsen''s Ironweed');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (26, 'A frozen cheesy bake made with cauliflower, great as a side dish or a vegetarian meal.', 'Home', 'Goldenrod', 5.49, '11/29/2026', 'Hispid Phyllostegia');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (27, 'Indoor Wi-Fi camera for home security.', 'Shoes', 'Puce', 89.99, '11/18/2026', 'Nettleleaf Sage');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (28, 'Spice blend for creating flavorful vegan taco filling.', 'Electronics', 'Goldenrod', 2.49, '10/9/2026', 'Snow Lichen');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (29, 'Quick-cooking couscous, great as a side or base.', 'Health', 'Fuscia', 2.49, '11/7/2026', 'Sagebrush Stickseed');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (30, 'Fresh greens and veggies for a quick Asian-inspired salad.', 'Outdoors', 'Orange', 3.99, '10/25/2026', 'Tall Tonguefern');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (31, 'Wild-caught salmon filets, perfect for grilling or baking.', 'Grocery', 'Pink', 12.99, '11/18/2026', 'Crowngrass');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (32, 'Sweetened powder for refreshing lemonade.', 'Music', 'Teal', 1.99, '10/23/2026', 'Cooper''s Rush');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (33, 'Relax and soothe tired feet with this foot spa.', 'Electronics', 'Turquoise', 59.99, '10/12/2026', 'Longbract Sedge');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (34, 'Light and fluffy cream cheese, perfect for bagels or cooking.', 'Industrial', 'Puce', 2.99, '11/7/2026', 'Greek Oregano');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (35, 'Crispy and juicy chicken tenders, perfect for dipping.', 'Jewelry', 'Goldenrod', 6.99, '12/9/2026', 'Para Grass');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (36, 'Supportive pillow that provides comfort while traveling.', 'Electronics', 'Red', 24.99, '9/24/2026', 'Leycesteria');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (37, 'A refreshing drink mix that combines sweet raspberries and tart lemons, perfect for summer.', 'Home', 'Aquamarine', 3.99, '11/9/2026', 'Ring Lichen');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (38, 'Compact yoga mat that folds for easy storage and transport.', 'Books', 'Violet', 29.99, '12/16/2026', 'Tyrol Knapweed');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (39, 'Everything you need to build a festive gingerbread house.', 'Music', 'Turquoise', 6.99, '10/19/2026', 'Smooth Draba');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (40, 'Creamy and delicious soup made with real butternut squash, ready to heat.', 'Baby', 'Purple', 3.49, '10/10/2026', 'Birdwing Treefern');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (41, 'Eco-friendly bags for picking up after your pet.', 'Outdoors', 'Red', 14.99, '11/27/2026', 'Alpine Hairgrass');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (42, 'Fun light that creates a disco atmosphere for parties.', 'Music', 'Turquoise', 19.99, '9/30/2026', 'Thompson''s Waterleaf');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (43, 'Soft and delicious garlic-infused flatbread, perfect for dipping.', 'Health', 'Aquamarine', 3.99, '12/3/2026', 'Fendler''s Lipfern');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (44, 'Automated stirring for your drinks with just a press of a button.', 'Outdoors', 'Pink', 19.99, '10/19/2026', 'Dominican Lovegrass');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (45, 'Nutritious and quick-cooking red lentils.', 'Toys', 'Aquamarine', 1.99, '12/7/2026', 'Andreaea Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (46, 'Essential tools for bike maintenance and repair.', 'Shoes', 'Goldenrod', 29.99, '10/2/2026', 'Manybristle Chinchweed');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (47, 'Space-saving collapsible bottle for outdoor activities.', 'Clothing', 'Aquamarine', 12.99, '11/21/2026', 'Latticevein Fern');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (48, 'Essential cotton tank top, perfect for layering.', 'Kids', 'Crimson', 14.99, '11/25/2026', 'Broadleaf Barbara''s Buttons');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (49, 'Sweet and tangy honey mustard dip for snacks.', 'Beauty', 'Mauv', 3.29, '11/6/2026', 'Brant''s Oak');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (50, 'Frozen pizza loaded with fresh vegetables and mozzarella cheese.', 'Shoes', 'Mauv', 8.99, '10/9/2026', 'Littleleaf Alumroot');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (51, 'Flexible molds perfect for baking cakes and pastries.', 'Toys', 'Crimson', 15.99, '11/5/2026', 'Gray Mulga');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (52, 'Corn on the cob seasoned with chili and lime for a spicy kick.', 'Industrial', 'Fuscia', 1.99, '10/20/2026', 'Douglas'' Dustymaiden');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (53, 'Freshly cut carrot sticks, perfect for snacking.', 'Electronics', 'Red', 2.49, '12/4/2026', 'Caracus Wigandia');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (54, 'Stone-ground mustard infused with craft beer for a gourmet touch.', 'Home', 'Red', 3.99, '10/6/2026', 'Lowland Bladderfern');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (55, 'Stylish case with magnetic closure for smartphones.', 'Sports', 'Blue', 19.99, '12/15/2026', 'Pylaisiadelpha Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (56, 'Nutty flavored lentils, perfect for soups and salads.', 'Shoes', 'Aquamarine', 3.99, '12/13/2026', 'Shoshone Ricegrass');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (57, 'A fragrant Indian spice blend for curries and stews.', 'Grocery', 'Teal', 2.79, '10/6/2026', 'Polytrichum Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (58, 'A smoky barbecue sauce, ideal for grilling and dipping.', 'Industrial', 'Crimson', 3.49, '10/24/2026', 'Balsampear');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (59, 'A colorful variety of crunchy veggie chips for snacking.', 'Jewelry', 'Goldenrod', 3.79, '12/5/2026', 'Birthwort');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (60, 'Flavorful lentil soup, perfect for a quick meal.', 'Books', 'Purple', 2.49, '11/2/2026', 'Rhachithecium Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (61, 'Savory, roasted nuts seasoned with garlic and parmesan.', 'Garden', 'Maroon', 4.89, '11/10/2026', 'Distichium Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (62, 'Soft and cozy slippers for indoor wear.', 'Computers', 'Goldenrod', 29.99, '11/19/2026', 'Jesuit''s Bark');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (63, 'Complete outdoor kit for camping and hiking.', 'Toys', 'Crimson', 89.99, '11/29/2026', 'Sweetclover');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (64, 'Quote wall art to inspire and motivate.', 'Grocery', 'Goldenrod', 24.99, '12/21/2026', 'Slender Dwarf Morning-glory');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (65, 'Juicy peach slices in syrup, perfect for desserts.', 'Shoes', 'Green', 2.49, '12/8/2026', 'Tubercle Dodder');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (66, 'Complete set for garden care with a handy carrying bag.', 'Toys', 'Purple', 39.99, '11/17/2026', 'Hypnum Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (67, 'Variety pack of sticky notes in different colors and sizes.', 'Outdoors', 'Indigo', 9.99, '11/3/2026', 'Elegant Mariposa Lily');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (68, 'Instant-read thermometer for accurate cooking temperatures.', 'Sports', 'Goldenrod', 19.99, '12/10/2026', 'Tiny Milkwort');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (69, 'Monitor and interact with your pet remotely with this camera.', 'Movies', 'Khaki', 149.99, '12/18/2026', 'Idaho Hymenopappus');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (70, 'Tool to check car engine codes and performance issues.', 'Books', 'Yellow', 49.99, '11/18/2026', 'Cryphaea Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (71, 'A cozy cable knit beanie to keep your head warm in winter.', 'Health', 'Pink', 19.99, '9/23/2026', 'Cyrtandra');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (72, 'Compact electric pot for hot pot dining at home.', 'Automotive', 'Blue', 49.99, '9/21/2026', 'Rhizoma Peanut');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (73, 'Complete outdoor kit for camping and hiking.', 'Movies', 'Indigo', 89.99, '12/18/2026', 'Tembien Clover');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (74, 'Charge multiple devices with this sleek charging station.', 'Jewelry', 'Puce', 39.99, '9/24/2026', 'Na''ena''e Pua Melemele');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (75, 'Rechargeable electric toothbrush with smart timer.', 'Jewelry', 'Purple', 49.95, '11/6/2026', 'Maui Stenogyne');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (76, 'Crispy and delicious biscotti flavored with cranberry and almond.', 'Jewelry', 'Mauv', 4.19, '10/21/2026', 'Claybank Beaksedge');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (77, 'Easy-to-set up tent designed for campers and hikers.', 'Industrial', 'Maroon', 129.99, '10/31/2026', 'Bur Oak');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (78, 'Eco-friendly string lights for outdoor decor.', 'Jewelry', 'Goldenrod', 29.99, '12/10/2026', 'Beavertail Pricklypear');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (79, 'Safe cleaning solution and tools for electronics screens.', 'Music', 'Fuscia', 15.99, '12/10/2026', 'Fineflower Gilia');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (80, 'Fast and accurate thermometer for grilling and cooking.', 'Automotive', 'Violet', 24.99, '10/14/2026', 'Hazelnut');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (81, 'Eco-friendly bamboo holder for toothbrushes.', 'Outdoors', 'Pink', 14.99, '12/5/2026', 'Sand Spikemoss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (82, 'Heavy-duty chain lock for securing bicycles.', 'Automotive', 'Mauv', 19.99, '11/15/2026', 'London Planetree');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (83, 'Crispy spring rolls filled with vegetables', 'Outdoors', 'Khaki', 6.49, '11/3/2026', 'Goosefoot Yellow Violet');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (84, 'Savory sauce perfect for pasta or dipping.', 'Clothing', 'Crimson', 3.29, '9/22/2026', 'Wedgescale Saltbush');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (85, 'Safe cleaning solution and tools for electronics screens.', 'Electronics', 'Indigo', 15.99, '9/27/2026', 'Cockleshell Lichen');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (86, 'Tangy whole grain mustard for sandwiches and dressings.', 'Outdoors', 'Crimson', 3.49, '11/14/2026', 'Sedge');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (87, 'Pack of ultra-soft microfiber cloths for cleaning.', 'Toys', 'Blue', 9.99, '10/30/2026', 'False Spleenwort');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (88, 'Traditional Korean fermented vegetables, packed with flavor.', 'Shoes', 'Maroon', 4.79, '11/27/2026', 'Hoptree');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (89, 'Blend of cheddar and mozzarella cheese, great for recipes.', 'Automotive', 'Fuscia', 4.29, '12/14/2026', 'Peanut');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (90, 'Instant-read thermometer for precise cooking temperatures.', 'Tools', 'Fuscia', 24.99, '11/18/2026', 'Angostura');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (91, 'Everything you need to make delicious spicy tuna rolls at home.', 'Shoes', 'Green', 8.99, '12/5/2026', 'Ceylon Spinach');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (92, 'Memory foam travel pillow for neck support.', 'Music', 'Blue', 22.99, '10/23/2026', 'Brachythecium Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (93, 'Fun tourist magnets from around the world for your fridge.', 'Computers', 'Yellow', 12.99, '11/4/2026', 'Kyhosia');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (94, 'Raw brown sugar, perfect for baking or sweetening drinks.', 'Tools', 'Teal', 1.79, '10/6/2026', 'Spilonema Lichen');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (95, 'Soft and pillowy gnocchi made from cauliflower, perfect with sauce.', 'Jewelry', 'Puce', 3.59, '12/9/2026', 'Didymodon Moss');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (96, 'Use this foam roller for effective post-workout recovery.', 'Toys', 'Purple', 29.99, '11/21/2026', 'Trefoil');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (97, 'Safe and easy-to-use nail clippers for pets.', 'Shoes', 'Yellow', 12.99, '12/19/2026', 'Hairy False Goldenaster');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (98, 'Delicious noodles tossed in a sesamegarlic sauce.', 'Tools', 'Maroon', 3.49, '10/4/2026', 'Gomidesia');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (99, 'Connect and control smart devices from one app.', 'Books', 'Red', 99.99, '10/17/2026', 'Lamp Rush');
insert into [CorporateData_Mountain1].[dbo].[SampleProducts] (Prod_id, Prod_Desc, Prod_Dept, Prod_Color, Prod_Price, Prod_Expires, Prod_Comments) values (100, 'Modern LED table lamp with touch control.', 'Garden', 'Turquoise', 29.99, '11/28/2026', 'Rocky Mountain Goosefoot');

-- Scripts start here:

-- 2. Create SQL Login
USE [master]
GO
CREATE LOGIN [supervisor1]
WITH PASSWORD = N'S0m3$tr0NgP@$$w0RdH3re!',
     DEFAULT_DATABASE = [master],   -- Default Database
     CHECK_EXPIRATION = OFF,        -- Expiration policy for the password?
     CHECK_POLICY = ON              -- Force complex password
GO

USE [master]
GO
CREATE LOGIN [supervisor2]
WITH PASSWORD = N'S0m3$tr0NgP@$$w0RdH3re!',
     DEFAULT_DATABASE = [master],   -- Default Database
     CHECK_EXPIRATION = OFF,        -- Expiration policy for the password?
     CHECK_POLICY = ON              -- Force complex password
GO

-- 3. Tools

-- https://learn.microsoft.com/en-us/sql/t-sql/functions/loginproperty-transact-sql?view=sql-server-ver17
SELECT LOGINPROPERTY('supervisor1', 'DaysUntilExpiration') AS [DaysUntilExpiration];
SELECT LOGINPROPERTY('supervisor2', 'DaysUntilExpiration') AS [DaysUntilExpiration];
-- 
SELECT LOGINPROPERTY('supervisor1', 'IsMustChange') AS [IsMustChange];
SELECT LOGINPROPERTY('supervisor2', 'IsMustChange') AS [IsMustChange];
-- 
SELECT LOGINPROPERTY('supervisor1', 'BadPasswordTime') AS [IsMustChange];
SELECT LOGINPROPERTY('supervisor2', 'BadPasswordTime') AS [IsMustChange];

--

SELECT name,
    is_policy_checked,
    is_expiration_checked,
    LOGINPROPERTY(name, 'IsMustChange') AS IsMustChange,
    LOGINPROPERTY(name, 'IsLocked') AS IsLocked,
    LOGINPROPERTY(name, 'LockoutTime') AS LockoutTime,
    LOGINPROPERTY(name, 'PasswordLastSetTime') AS PasswordLastSetTime,
    LOGINPROPERTY(name, 'IsExpired') AS IsExpired,
    LOGINPROPERTY(name, 'BadPasswordCount') AS BadPasswordCount,
    LOGINPROPERTY(name, 'BadPasswordTime') AS BadPasswordTime,
    LOGINPROPERTY(name, 'HistoryLength') AS HistoryLength,
    modify_date
FROM sys.sql_logins
Where name like 'supervisor%';

-- View password expiration days
SELECT
    name AS LoginName,
    LOGINPROPERTY(name, 'PasswordLastSetTime') AS PasswordLastSetTime,
    ISNULL(CONVERT(varchar(100), LOGINPROPERTY(name, 'DaysUntilExpiration')), 'Never Expire') AS DaysUntilExpiration,
    CASE WHEN LOGINPROPERTY(name, 'IsExpired') = 1 THEN 'TRUE' ELSE 'FALSE' END AS IsExpired,
    CASE WHEN LOGINPROPERTY(name, 'IsMustChange') = 1 THEN 'TRUE' ELSE 'FALSE' END AS IsMustChange,
    CASE WHEN is_expiration_checked = 1 THEN 'TRUE' ELSE 'FALSE' END AS PasswordExpireChecked
FROM
    sys.sql_logins
WHERE
    name NOT LIKE '##%' -- Exclude system logins
    AND is_disabled = 0 -- Exclude disabled logins
ORDER BY
    LoginName;

--

-- 4. Create database user (user mapping)
USE [CorporateData_East1];
GO
CREATE USER [supervisor1] FOR LOGIN [supervisor1] WITH DEFAULT_SCHEMA=[dbo];
GO
-- Optional Roles
ALTER ROLE [db_datareader] ADD MEMBER [supervisor1] -- Can read all tables
ALTER ROLE [db_datawriter] ADD MEMBER [supervisor1] -- Can write all tables
ALTER ROLE [db_ddladmin] ADD MEMBER [supervisor1]   -- Can run DDL (CREATE, ALTER, DROP)
GO

-- 5. Grants

USE [CorporateData_East1];
GO
-- Select name from sys.tables
-- a. Grant permission: All basic permissions on a table
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.SamplePeople TO [supervisor1];
GO

-- b. Grant permission: All basic permissions on a table, except for DELETE
GRANT SELECT, INSERT, UPDATE ON dbo.SampleProducts TO [supervisor1];
GO

GRANT DELETE ON dbo.SampleProducts TO [supervisor1];
GO

-- With Grant: Allows the user to grant the permission to another user
GRANT INSERT, UPDATE ON dbo.SampleProducts TO [supervisor2] WITH GRANT OPTION;
GO

-- 6. Other object permissions
USE [CorporateData_East1];
GO

-- a. Stored Procedure: execute permission
GRANT EXECUTE ON OBJECT::dbo.sp_YourStoredProc TO [supervisor1];
GO

-- b. Function: execute permission
-- Works for scalar or table-valued functions
GRANT EXECUTE ON OBJECT::dbo.fn_YourFunction TO [supervisor1];
GO

-- c. View: select permission
GRANT SELECT ON OBJECT::dbo.vw_YourView TO [supervisor1];
GO

-- 5. Revoke permissions
-- UPDATE
REVOKE UPDATE ON OBJECT::dbo.SampleProducts FROM [supervisor1];
GO
-- DELETE
REVOKE DELETE ON OBJECT::dbo.SampleProducts FROM [supervisor1];
GO

-- 7. List logins
Select sid, 
       name,
       type,
       type_desc,
       default_database_name,
       create_date,
       modify_date,
       default_language_name
From master.sys.server_principals
Where type IN ( 'S', 'U' )
      AND 
      name not like '%#%';

-- With password hash
Select sid,
       name,
       password_hash -- varbinary(256)
From master.sys.sql_logins
Where name not like '%#%'

-- 8. Recreate Logins (SQL + Windows)
SELECT 
    sp.sid AS SID,
    sp.name AS LoginName,
    sp.type_desc AS LoginType,
    sl.password_hash AS PasswordHash,
    CASE 
        WHEN sp.type = 'S' THEN 
            'USE [master] 
             CREATE LOGIN [' + sp.name + '] 
             WITH PASSWORD = ' + CONVERT(varchar(max), sl.password_hash, 1) + ' HASHED, 
             SID = ' + CONVERT(varchar(max), sp.sid, 1) + ', 
             CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF' 
        WHEN sp.type IN ('U','G') THEN 
            'USE [master] 
             CREATE LOGIN [' + sp.name + '] 
             FROM WINDOWS 
             WITH SID = ' + CONVERT(varchar(max), sp.sid, 1)
    END AS CreateLoginScript
FROM sys.server_principals AS sp
LEFT JOIN sys.sql_logins AS sl
    ON sp.principal_id = sl.principal_id
WHERE sp.type IN ('S', 'U', 'G')   -- SQL logins + Windows users + groups
  AND sp.name NOT LIKE '%#%'       -- Exclude certificates, etc.
  AND sp.name NOT LIKE '##%'       -- Exclude internal system accounts
ORDER BY sp.name;

-- 9. Drop User / Login
USE [CorporateData_East1];
GO

-- Verify user
DECLARE @UserName VARCHAR(128)
SET @UserName = 'Supervisor1'
Select name
From sys.database_principals
WHERE name = @UserName


-- a. Drop the user from the database
IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'Supervisor1')
    DROP USER Supervisor1;
GO

USE [master];
GO

DECLARE @UserName VARCHAR(128)
SET @UserName = 'Supervisor1'
Select name
From sys.sql_logins
WHERE name = @UserName
GO 

-- b. Drop the login from the instance
IF EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'Supervisor1')
    DROP LOGIN [Supervisor1];
GO