-- Create database folders
/*
MD C:\SQLDATA\StackOverflow2010New\PRIMARY
MD C:\SQLDATA\StackOverflow2010New\TRANSLOG
MD C:\SQLDATA\StackOverflow2010New\TBL
MD C:\SQLDATA\StackOverflow2010New\LOB
*/


USE [master]
GO

CREATE DATABASE [StackOverflow2010New]
 CONTAINMENT = NONE
 ON PRIMARY 
(NAME = N'[PRIMARY]_[StackOverflow2010New]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\PRIMARY\[PRIMARY]_[StackOverflow2010New].mdf' , SIZE = 512MB , FILEGROWTH = 0 )
 LOG ON 
(NAME = N'[TRANSLOG]_[StackOverflow2010New]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TRANSLOG\[TRANSLOG]_[StackOverflow2010New].ldf' , SIZE = 512MB , FILEGROWTH = 64MB)
COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [StackOverflow2010New] SET COMPATIBILITY_LEVEL = 160 -- SQL Server 2022
ALTER DATABASE [StackOverflow2010New] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [StackOverflow2010New] SET ANSI_NULLS OFF 
ALTER DATABASE [StackOverflow2010New] SET ANSI_PADDING OFF 
ALTER DATABASE [StackOverflow2010New] SET ANSI_WARNINGS OFF 
ALTER DATABASE [StackOverflow2010New] SET ARITHABORT OFF 
ALTER DATABASE [StackOverflow2010New] SET AUTO_CLOSE OFF 
ALTER DATABASE [StackOverflow2010New] SET AUTO_SHRINK OFF 
ALTER DATABASE [StackOverflow2010New] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
ALTER DATABASE [StackOverflow2010New] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [StackOverflow2010New] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [StackOverflow2010New] SET CURSOR_DEFAULT GLOBAL 
ALTER DATABASE [StackOverflow2010New] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [StackOverflow2010New] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [StackOverflow2010New] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [StackOverflow2010New] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [StackOverflow2010New] SET DISABLE_BROKER 
ALTER DATABASE [StackOverflow2010New] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [StackOverflow2010New] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [StackOverflow2010New] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [StackOverflow2010New] SET READ_COMMITTED_SNAPSHOT ON -- When it is turned to ON, row versioning is used instead of locking
ALTER DATABASE [StackOverflow2010New] SET READ_WRITE 
ALTER DATABASE [StackOverflow2010New] SET RECOVERY SIMPLE -- Chage to Full when migration is completed (see lines 67 ~ 70)
ALTER DATABASE [StackOverflow2010New] SET MULTI_USER 
ALTER DATABASE [StackOverflow2010New] SET PAGE_VERIFY CHECKSUM 
ALTER DATABASE [StackOverflow2010New] SET TARGET_RECOVERY_TIME = 60 SECONDS -- Recommended value
GO

ALTER DATABASE [StackOverflow2010New] SET DELAYED_DURABILITY = DISABLED 
GO
USE [StackOverflow2010New]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [StackOverflow2010New] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

/* -- Run after data migration
USE [master]
GO
ALTER DATABASE [StackOverflow2010New] SET RECOVERY FULL WITH NO_WAIT
GO
*/


USE [StackOverflow2010New]
GO

-- Filegroups
-- Tables
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_Badges]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_Comments]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_LinkTypes]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_PostLinks]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_Posts]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_PostTypes]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_Users]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_Votes]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_TBL_dbo_VoteTypes]
-- LOBs
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_LOB_dbo_Posts]
ALTER DATABASE [StackOverflow2010New] ADD FILEGROUP [FG_LOB_dbo_Users]

-- Files
-- Tables
-- Large table
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Posts]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Posts]_[1].ndf', SIZE = 1280MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Posts]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Posts]_[2]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Posts]_[2].ndf', SIZE = 1280MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Posts]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Posts]_[3]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Posts]_[3].ndf', SIZE = 1280MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Posts]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Posts]_[4]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Posts]_[4].ndf', SIZE = 1280MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Posts]
-- Large table
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Comments]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Comments]_[1].ndf', SIZE = 320MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Comments]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Comments]_[2]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Comments]_[2].ndf', SIZE = 320MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Comments]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Comments]_[3]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Comments]_[3].ndf', SIZE = 320MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Comments]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Comments]_[4]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Comments]_[4].ndf', SIZE = 320MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Comments]
-- Small tables
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Votes]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Votes]_[1].ndf', SIZE = 360MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Votes]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Users]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Users]_[1].ndf', SIZE = 60MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Users]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_Badges]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_Badges]_[1].ndf', SIZE = 1MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_Badges]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_PostLinks]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_PostLinks]_[1].ndf', SIZE = 1MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_PostLinks]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_LinkTypes]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_LinkTypes]_[1].ndf', SIZE = 1MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_LinkTypes]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_VoteTypes]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_VoteTypes]_[1].ndf', SIZE = 1MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_VoteTypes]
ALTER DATABASE [StackOverflow2010New] ADD FILE ( NAME = N'[TBL]_[dbo_PostTypes]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\TBL\[TBL]_[dbo_PostTypes]_[1].ndf', SIZE = 1MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_TBL_dbo_PostTypes]
-- LOBs
ALTER DATABASE [StackOverflow2010New] ADD FILE (NAME = N'[LOB]_[dbo_Posts]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\LOB\[LOB]_[dbo_Posts]_[1].ndf', SIZE = 550MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_LOB_dbo_Posts]
ALTER DATABASE [StackOverflow2010New] ADD FILE (NAME = N'[LOB]_[dbo_Users]_[1]', FILENAME = N'C:\SQLDATA\StackOverflow2010New\LOB\[LOB]_[dbo_Users]_[1].ndf', SIZE = 1MB , MAXSIZE = UNLIMITED ,FILEGROWTH = 10% ) TO FILEGROUP [FG_LOB_dbo_Users]

-- Tables

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Votes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PostId] [int] NOT NULL,
	[UserId] [int] NULL,
	[BountyAmount] [int] NULL,
	[VoteTypeId] [int] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Votes__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_Votes]
) ON [FG_TBL_dbo_Votes]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Comments](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[PostId] [int] NOT NULL,
	[Score] [int] NULL,
	[Text] [nvarchar](700) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_Comments__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,	
		ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_Comments]
) ON [FG_TBL_dbo_Comments]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Posts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AcceptedAnswerId] [int] NULL,
	[AnswerCount] [int] NULL,
	[Body] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClosedDate] [datetime] NULL,
	[CommentCount] [int] NULL,
	[CommunityOwnedDate] [datetime] NULL,
	[CreationDate] [datetime] NOT NULL,
	[FavoriteCount] [int] NULL,
	[LastActivityDate] [datetime] NOT NULL,
	[LastEditDate] [datetime] NULL,
	[LastEditorDisplayName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastEditorUserId] [int] NULL,
	[OwnerUserId] [int] NULL,
	[ParentId] [int] NULL,
	[PostTypeId] [int] NOT NULL,
	[Score] [int] NOT NULL,
	[Tags] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Title] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ViewCount] [int] NOT NULL,
 CONSTRAINT [PK_Posts__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_Posts]
) ON [FG_TBL_dbo_Posts] TEXTIMAGE_ON [FG_LOB_dbo_Posts]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Badges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UserId] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Badges__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_Badges]
) ON [FG_TBL_dbo_Badges]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AboutMe] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Age] [int] NULL,
	[CreationDate] [datetime] NOT NULL,
	[DisplayName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DownVotes] [int] NOT NULL,
	[EmailHash] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastAccessDate] [datetime] NOT NULL,
	[Location] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Reputation] [int] NOT NULL,
	[UpVotes] [int] NOT NULL,
	[Views] [int] NOT NULL,
	[WebsiteUrl] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccountId] [int] NULL,
 CONSTRAINT [PK_Users_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_Users]
) ON [FG_TBL_dbo_Users] TEXTIMAGE_ON [FG_LOB_dbo_Users]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PostLinks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[PostId] [int] NOT NULL,
	[RelatedPostId] [int] NOT NULL,
	[LinkTypeId] [int] NOT NULL,
 CONSTRAINT [PK_PostLinks__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_PostLinks]
) ON [FG_TBL_dbo_PostLinks]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VoteTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_VoteType__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_VoteTypes]
) ON [FG_TBL_dbo_VoteTypes]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PostTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_PostTypes__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, 
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_PostTypes]
) ON [FG_TBL_dbo_PostTypes]
GO

--

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LinkTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_LinkTypes__Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,	
		OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [FG_TBL_dbo_LinkTypes]
) ON [FG_TBL_dbo_LinkTypes]
GO